name: api-secti
services:
- name: backend
  github:
    repo: gsvirgilli/api-secti-go-privado
    branch: principal
  dockerfile_path: backend/Dockerfile
  source_dir: backend
  http_port: 3000
  envs:
  - key: NODE_ENV
    value: production
  - key: DATABASE_HOST
    scope: RUN_AND_BUILD_TIME
  - key: DATABASE_USER
    scope: RUN_AND_BUILD_TIME
  - key: DATABASE_PASSWORD
    scope: RUN_AND_BUILD_TIME
  - key: DATABASE_NAME
    scope: RUN_AND_BUILD_TIME
  - key: DATABASE_PORT
    value: "3306"
  - key: JWT_SECRET
    scope: RUN_AND_BUILD_TIME
  - key: JWT_EXPIRES_IN
    value: "1d"
  - key: APP_PORT
    value: "3000"

- name: frontend
  github:
    repo: gsvirgilli/api-secti-go-privado
    branch: principal
  dockerfile_path: frontend/Dockerfile
  source_dir: frontend
  http_port: 3000
  envs:
  - key: VITE_API_URL
    value: ""
